name: Deploy GitHub Pages

concurrency:
  cancel-in-progress: true
  group: github-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build
        run: bun run build

      - name: Prepare GitHub Pages artifact
        shell: bash
        run: |
          set -euo pipefail

          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
